language: c
dist: trusty
sudo: false

matrix:
  include:
   # Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc7
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-7','libxmu-dev']
      env: GCCVER='7' C_COMPILER='gcc-7'

    # 4/ OSX GCC Builds
    #- os: osx
    #  osx_image: xcode8.3
    #  compiler: gcc
    #  env: GCCVER='7' CXX_COMPILER='g++-7' C_COMPILER='gcc-7'

before_script:
## OSX
  - cd ${TRAVIS_BUILD_DIR} 
  - export CC=${C_COMPILER}
  - export ACEDB_MACHINE=LINUX_4_OPT
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ACEDB_MACHINE=MAC_X_64_OPT   ; fi  
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc    ; fi  
# an example library (here libgmp) that is downloaded, configure + make + installed.
#  - wget --progress=dot:mega https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2 ; tar xjf gmp-6.1.2.tar.bz2 ; cd gmp-6.1.2 ; ./configure --enable-cxx --prefix=$(pwd)/../usr/local ; make -j ; make install ; cd .. ;      
  # linux only
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export AR=gcc-ar-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export RANLIB=gcc-ranlib-${GCCVER} ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NM=gcc-nm-${GCCVER} ; fi
  #  choose target branch for redeployment on github
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export TARGETBRANCH=gh-pages ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export TARGETBRANCH=osx ; fi


script :
  - make libs
  - make ace
  - make acembly
  - make other
  - make acext
  - make tools
  - make all
  # - mkdir website
  # - touch website/hello.html
  # - cp bin.$ACEDB_MACHINE/* website/
#  - mkdir usr && mkdir usr/local
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --progress=dot:mega https://lip6.github.io/libDDD/linux.tgz ; tar xzf linux.tgz ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget --progress=dot:mega https://github.com/lip6/libDDD/raw/osx/osx.tgz ; tar xzf osx.tgz ; fi
#  my configurte using the libs and deps installed above in $pwd/usr/local
#  - ./configure --enable-nolto --prefix=$PWD/usr/local/  --with-libexpat=$PWD/usr/local/  --with-gmp=$PWD/usr/local/ --with-antlrc=$PWD/usr/local/   --with-antlrjar=$PWD/usr/local/lib/antlr-3.4-complete.jar CPPFLAGS="-I$(pwd)/usr/local/include" LDFLAGS="-L$(pwd)/usr/local/lib" || cat config.log ; 
#  - ( rc=0 ; for TEST in *.data ; do travis_wait ./run_test.pl $TEST || rc=$? ; done; exit $rc) 

# - cd ..
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then strip bin/its-reach ; fi
  # linux only
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then strip -s bin/its-reach ; fi
#  - cp bin/its-reach website/its-reach
# linux only
#  - make install
#  - tar cvzf $TRAVIS_OS_NAME.tgz usr/
# - mv $TRAVIS_OS_NAME.tgz website/
#  - make dist
#  - mv its*.tar.gz website/


deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: website/
#  target_branch: $TARGETBRANCH
#  on:
#    branch: master

#after_deploy:
#  - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json"   -H "Travis-API-Version:3" -H "Authorization:token $APITOKEN" -d '{"request":{"message":"Triggered by LibITS build.","branch":"master"}}' https://api.travis-ci.org/repo/lip6%2FITS-CTL/requests

    
